{
 "title": "CPU Usage Timeseries",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "targets": [
    { "expr": "node_cpu_seconds_total" }
   ]
  }
 ]
}
{
 "title": "Memory Gauge",
 "panels": [
  {
   "title": "Consumed Memory",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  }
 ]
}
{
 "title": "Disk Usage Stat",
 "panels": [
  {
   "title": "Disk Available",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes" }
   ]
  }
 ]
}
{
 "title": "Pods Table",
 "panels": [
  {
   "title": "Pods Status",
   "type": "table",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "targets": [
    { "expr": "kube_pod_info" }
   ]
  }
 ]
}